name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Object tracking test
      id: object-tracking-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Object tracking test
        setup-command: pip install -r requriements.txt
        command: python -m pytest
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        OBJECT-TRACKING-TEST_RESULTS: "${{steps.object-tracking-test.outputs.result}}"
      with:
        runners: object-tracking-test
